version: 2.1

jobs:
  build-and-upload:
    macos:
      xcode: 16.1.0
    environment:
      CERTIFICATE_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Extract Workspace and Scheme
          command: |
            xcodebuild -list -json

            # Check if xcworkspace exists
            if ls *.xcworkspace 1> /dev/null 2>&1; then
              WORKSPACE_NAME=$(ls | grep xcworkspace | head -n 1)
              echo "export WORKSPACE_NAME=$WORKSPACE_NAME" >> $BASH_ENV
              SCHEME_NAME=$(xcodebuild -workspace "$WORKSPACE_NAME" -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
            else
              PROJECT_NAME=$(ls | grep xcodeproj | head -n 1)
              echo "export PROJECT_NAME=$PROJECT_NAME" >> $BASH_ENV
              SCHEME_NAME=$(xcodebuild -project "$PROJECT_NAME" -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
            fi
            echo "export SCHEME_NAME=$SCHEME_NAME" >> $BASH_ENV
            source $BASH_ENV            
      
      - run:
          name: 키체인 설정
          command: |
            security create-keychain -p circle circle.keychain
            security default-keychain -s circle.keychain
            security unlock-keychain -p circle circle.keychain
            security set-keychain-settings -t 3600 -l ~/Library/Keychains/circle.keychain
      
      - run:
          name: 인증서 설치
          command: |
            security import ./distribution.p12 -k ~/Library/Keychains/circle.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k circle circle.keychain
      
      - run:
          name: 프로비저닝 프로파일 설치
          command: |
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp ./profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      
      - run:
          name: 빌드
          command: |
            if [ ! -z "$WORKSPACE_NAME" ]; then
              xcodebuild \
                -workspace "$WORKSPACE_NAME" \
                -scheme "$SCHEME_NAME" \
                -configuration Release \
                -archivePath "${SCHEME_NAME}.xcarchive" \
                archive
            else
              xcodebuild \
                -project "$PROJECT_NAME" \
                -scheme "$SCHEME_NAME" \
                -configuration Release \
                -archivePath "${SCHEME_NAME}.xcarchive" \
                archive
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-upload
