version: 2.1

jobs:
  build-and-upload:
    macos:
      xcode: 16.1.0
    environment:
      CERTIFICATE_PASSWORD: "123456"
      TEAM_ID: "22X77ENQ2H"
      APPLE_ID: "puzznic@inka.co.kr"
      APP_SPECIFIC_PASSWORD: "qbrz-hmfz-robj-eohm"
      YOUR_PROVISIONING_PROFILE_NAME: "AppSealing Wildcard Distribution Profile"
    steps:
      - checkout

      - run:
          name: Extract Workspace and Scheme
          command: |
            # Check if xcworkspace exists
            if ls *.xcworkspace 1> /dev/null 2>&1; then
              WORKSPACE_NAME=$(ls | grep xcworkspace | head -n 1)
              echo "export WORKSPACE_NAME=$WORKSPACE_NAME" >> $BASH_ENV
              SCHEME_NAME=$(xcodebuild -workspace "$WORKSPACE_NAME" -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
            else
              PROJECT_NAME=$(ls | grep xcodeproj | head -n 1)
              echo "export PROJECT_NAME=$PROJECT_NAME" >> $BASH_ENV
              SCHEME_NAME=$(xcodebuild -project "$PROJECT_NAME" -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
            fi
            echo "export SCHEME_NAME=$SCHEME_NAME" >> $BASH_ENV

            echo PROJECT_NAME = ${PROJECT_NAME}
            echo WORKSPACE_NAME = ${WORKSPACE_NAME}
            echo SCHEME_NAME = ${SCHEME_NAME}

            # Extract Bundle ID and properly escape it
            if [ ! -z "$WORKSPACE_NAME" ]; then
              BUNDLE_ID=$(xcodebuild -workspace "$WORKSPACE_NAME" -scheme "$SCHEME_NAME" -showBuildSettings | grep "PRODUCT_BUNDLE_IDENTIFIER" | sed 's/.*= //' | tr -d '[:space:]')
            else
              BUNDLE_ID=$(xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME_NAME" -showBuildSettings | grep "PRODUCT_BUNDLE_IDENTIFIER" | sed 's/.*= //' | tr -d '[:space:]')
            fi

            echo "BUNDLE_ID=\"$BUNDLE_ID\"" >> $BASH_ENV
            echo Bundle ID = ${BUNDLE_ID}
            source $BASH_ENV

      - run:
          name: 키체인 설정
          command: |
            security create-keychain -p circle circle.keychain
            security default-keychain -s circle.keychain
            security unlock-keychain -p circle circle.keychain
            security set-keychain-settings -t 3600 -l ~/Library/Keychains/circle.keychain
      
      - run:
          name: 인증서 설치
          command: |
            security import ./distribution.p12 -k ~/Library/Keychains/circle.keychain -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k circle circle.keychain
      
      - run:
          name: 프로비저닝 프로파일 설치
          command: |
            mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/
            cp ./profile.mobileprovision ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles/
      
      - run:
          name: Generate exportOptions.plist
          command: |
            cat > ./exportOptions.plist \<< EOL
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>method</key>
                <string>app-store</string>
                <key>teamID</key>
                <string>${TEAM_ID}</string>
                <key>signingStyle</key>
                <string>manual</string>
                <key>stripSwiftSymbols</key>
                <true/>
                <key>uploadBitcode</key>
                <false/>
                <key>uploadSymbols</key>
                <true/>
                <key>provisioningProfiles</key>
                <dict>
                    <key>${BUNDLE_ID}</key>
                    <string>${YOUR_PROVISIONING_PROFILE_NAME}</string>
                </dict>                
            </dict>
            </plist>
            EOL
            cat ./exportOptions.plist

      - run:
          name: 빌드
          command: |
            if [ ! -z "$WORKSPACE_NAME" ]; then
              xcodebuild \
                -workspace "$WORKSPACE_NAME" \
                -scheme "$SCHEME_NAME" \
                -configuration Release \
                -destination 'generic/platform=iOS' \
                -allowProvisioningUpdates \
                -archivePath "${SCHEME_NAME}.xcarchive" \
                archive
            else
              xcodebuild \
                -project "$PROJECT_NAME" \
                -scheme "$SCHEME_NAME" \
                -configuration Release \
                -destination 'generic/platform=iOS' \
                -allowProvisioningUpdates \
                -archivePath "${SCHEME_NAME}.xcarchive" \
                archive
            fi

      - run:
          name: Export IPA
          command: |
            xcodebuild \
              -exportArchive \
              -archivePath "${SCHEME_NAME}.xcarchive" \
              -exportOptionsPlist ./exportOptions.plist \
              -exportPath ./artifacts

      - run:
          name: App Store Connect에 업로드
          command: |
            xcrun altool --upload-app \
              --type ios \
              --file "./artifacts/${SCHEME_NAME}.ipa" \
              --username "$APPLE_ID" \
              --password "$APP_SPECIFIC_PASSWORD" \
              --verbose            

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-upload
